Welcome to the Lost Mine!
This adventure was created by Joe Peterson and De Crandell. 2               3               3               2               3               2               4 A large dome of glassy rock surrounds you.  In the middle of
the room is a glass case with a miner's pick safely housed
inside.  The room exits to the south..S....CUT GLASS,CUT CASE:GLASS CUTTER+PICK:After the pick falls out, the glass repairs itself and another
pick materializes inside the case.You are in a large empty room.  The only thing unusual is a
door in the ceiling with a handle.  There is a low crawl to the
east...E...OPEN DOOR,PULL HANDLE[U:The door falls open.You are in an open north/south passage.  A low crawl goes west.NS.W..The walls in this room seem to be collapsing.  Loose sand
covers the floor, and among the sand grains are tiny particles
of glass.  A passage exits to the south.BUCKET OF SAND.S....You are in the mine elevator.  It is on the lower level.
The doors open to the east, and there is a button on the wall...E...PUSH BUTTON,PRESS BUTTON/0,3,1:There is a humming sound as the elevator does its stuff.There is a wide open passage to the north and a small tunnel
to the east.  To the west is the mine elevator.N.EW..A ghastly sight lies before you!  Sitting against the wall is a
skeleton.  It looks like he hasn't eaten for a hundred years!
Passages go north, east, and west.N.EW..FEED SKELETON:CONTAINER OF FOOD%CONTAINER OF FOOD,EMPTY CONTAINER:The skeleton looks at you and says,
     "Ashes to ashes, rock to dust -
      Just say ZWOOF, me you must trust..."Extending from the wall is the bottom of a long chute.
There is an exit to the west....W..U,UP,CLIMB,CLIMB CHUTE,GO CHUTE:The chute is too slick to climb!-......Suddenly the mining car starts rolling toward you!
You make a futile attempt to run away - but you can't run
thirty miles per hour!  You are dead.You are in a gaping cavern.  To the west a railroad track
extends into the distance.  On the track is an old mining car
chained to the wall.  To the south is a clear passage..S.W..CUT CHAIN,SAW CHAIN:HACKSAW!The chain breaks, and the car starts to roll.  You jump in just
in time!  The car goes faster and faster as it crosses a
suspension bridge.  You then roll to a stop safely outside the
mine.
                           YOU WIN!Scattered about you are scraps and shavings of wood and metal.
A single bare electrical wire hangs from the ceiling.  There
are tunnels to the south and east..SE...GRAB WIRE,TOUCH WIRE,HOLD WIRE,PULL WIRE,GET WIRE,TAKE WIRE/1,1,2:You feel a tremendous surge of energy pass through your body as
you are pulled into the wire.  You emerge from an empty light
socket.You are in a long room with a pit stretching out before you to
the south.  Across the pit you can see another room.  There is
a tunnel to the west....W..THROW SPEAR,CHUCK SPEAR:SPEAR AND ROPE-SPEAR AND ROPE;[S:The spear flies across the pit with the rope trailing behind.
It penetrates the rock on the opposite side, and the rope
creates a bridge to the south.You are in a hands and knees passage that exits to the south
and east..SE...There is a clear passage to the north and crawls to the east
and west.N.EW..The walls of this room are covered with pictures of lightning
bolts.  Tunnels lead north and south, and a low crawl goes
west.NS.W..There is a spear protruding from the south wall.  To the north
is the pit you just crossed.  A rope creates a bridge between
the spear and the far side of the pit.COINN.....You are in a small room with debris everywhere.  There is a
small door in the floor which leads down to a lower level.
To the north is a low crawl.N....DYou have entered a small room with a low ceiling.  Cobwebs
hang from the walls in every direction.  To the south is a wall
of crumbled rock.CONTAINER OF FOOD......PICK ROCK,HIT ROCK,CHOP ROCK,DIG ROCK:PICK/1,3,1:You dig through the rock and emerge on the other side.
The wall behind you crumbles!You are walking through a winding tunnel.  The walls glimmer as
if they were metallic.  The tunnel exits to the north and east.N.E...+COIN/2,1,1:ZAP!!!  A bolt of lightening suddenly strikes the coin and
thrusts you out of the room.You are in a large empty room.  At one end is a slot with a
message under it.  The message says:
     "Insert coin in slot to get an edge on this adventure!"
High above you is a steel grate, which lights the room with abeam of sunlight.  There is an exit to the west....W..INSERT COIN,DROP COIN:COIN-COIN;+HACKSAW:A hacksaw appears on the floor in front of you.You are in the mine elevator.  It is on the upper level.
The doors open to the east, and there is a button on the wall...E...PUSH BUTTON,PRESS BUTTON/0,3,0:There is a hum as you feel yourself moving downward.You are in an east/west passage.  There was once a passage
going north, but it is now blocked by fallen rock...EW..PICK ROCK,CHOP ROCK,HIT ROCK,DIG ROCK:PICK/1,2,1:You break through the rock and fall into the next room.
The wall caves in behind you!You are standing on a platform jutting out from the rock wall.
A rope is dangling from the cliff above.  The rock opens to the
west....WU.CLIMB,CLIMB ROPE,CLIMB UP=UThe walls of this room are very smooth.  In one wall is a chute
sloping down into the darkness.  There is a tunnel to the
south..S....D,DOWN,SLIDE,SLIDE DOWN,SLIDE CHUTE,GO CHUTE/3,3,0:You feel as if you're falling through space as you slide down
the long dark chute.  Suddenly, you hit something hard - it's
the floor of a room!Passages go south and east, and a dark tunnel goes north.NSE...You are standing below an empty light socket.  The room exits
to the west....W..This room looks as if it was once a worship place.  There is a
round slab of rock in the center of the room.  Imbedded in the
rock is the point of a spear.  The spear is standing verticallyin the slab and has a rope tied to the end.  A passage leads
out to the north.N.....ZWOOF,SAY ZWOOF+SPEAR AND ROPE:The rock slab turns to dust, and the spear falls out.
The image of another spear magically appears in place of the
real one.Sand covers the ground all around you.  Under your feet is a
steel grate through which you can see a large room.  Paths go
south and east..SE...DROP COIN,THROW COIN:COIN#3,2,1>COIN:Ker-plink!  The coin drops through the grate.You are standing on a sand covered plateau.  To one side is a
big boulder.  To the south you see a tree growing out of the
side of the cliff with a rope tied to the very end.  A clear
path leads west..S.W..MOVE BOULDER,PUSH BOULDER,ROLL BOULDER,LIFT BOULDER+ROPE:There is a rope hidden under the boulder!You are standing at the edge of a cliff.  Far below you a
platform extends from the cliff.  There is no way to climb down
on the rocks.  Off to one side is a cactus, and a path exits to
the north.N.....DROP ROPE,THROW ROPE,TOSS ROPE,TIE ROPE:ROPE-ROPE;[D:The rope is now hanging over the edge.-......Just as you reach for the rope...
SNAP!!!  The tree cracks then breaks -
You fall to your death.POUR SAND,POUR BUCKET,EMPTY BUCKET,DUMP SAND,DUMP BUCKET,THROW SAND:BUCKET OF SAND+GLASS CUTTER;%BUCKET OF SAND,EMPTY BUCKET:The sand spills out to reveal a glass cutter!CLIMB,CLIMB ROPE,CLIMB DOWN=D2,3,2BREAK GLASS,CRACK GLASS,BREAK CASE,CRACK CASEYour ears are pierced by a screeching siren!
A group of guards comes rushing in and riddles you with bullets!You are dead.1,1,0