#!/bin/bash

cd ../images

cp explore_icon_512x512.png explore_icon_114x114.png
mogrify -resize 114x114 +gamma 0.0 explore_icon_114x114.png
cp explore_icon_512x512.png explore_icon_96x96.png
mogrify -resize 96x96 +gamma 0.0 explore_icon_96x96.png
cp explore_icon_512x512.png explore_icon_72x72.png
mogrify -resize 72x72 +gamma 0.0 explore_icon_72x72.png
cp explore_icon_512x512.png explore_icon_48x48.png
mogrify -resize 48x48 +gamma 0.0 explore_icon_48x48.png
cp explore_icon_512x512.png explore_icon_36x36.png
mogrify -resize 36x36 +gamma 0.0 explore_icon_36x36.png
